### ISSUE TITLE
ActiveRecord spec disaster

### ISSUE THREAD

**Issue by kswope** [igrigorik/em-synchrony#159]
I cannot get a single ActiveRecord test to succeed.  I've had no luck either on my mac or on a vanilla ubuntu server install.  Ruby 1.9.3 or 2.0.0.  Its always the same.  Looks like each test locks up, probably a fiber gets stuck, and mysql times out.  Under what circumstances are people getting these tests to succeed?

running
rspec spec/activerecord_spec.rb 

    1) Fiberized ActiveRecord driver for mysql2 should establish AR connection
       Failure/Error: EventMachine.synchrony do
       ActiveRecord::StatementInvalid:
         Mysql2::Error: Lock wait timeout exceeded; try restarting transaction: DELETE FROM `widgets`
       # /home/ubuntu/.rvm/gems/ruby-2.0.0-p195/gems/em-synchrony-1.0.3/lib/em-synchrony/mysql2.rb:14:in `async_result'
       # /home/ubuntu/.rvm/gems/ruby-2.0.0-p195/gems/em-synchrony-1.0.3/lib/em-synchrony/mysql2.rb:14:in `notify_readable'
       # /home/ubuntu/.rvm/gems/ruby-1.9.3-p429/bundler/gems/eventmachine-dd675e4d0617/lib/eventmachine.rb:187:in `run_machine'
       # /home/ubuntu/.rvm/gems/ruby-1.9.3-p429/bundler/gems/eventmachine-dd675e4d0617/lib/eventmachine.rb:187:in `run'
       # /home/ubuntu/.rvm/gems/ruby-2.0.0-p195/gems/em-synchrony-1.0.3/lib/em-synchrony.rb:38:in `synchrony'
       # /home/ubuntu/.rvm/gems/ruby-2.0.0-p195/gems/em-synchrony-1.0.3/spec/activerecord_spec.rb:30:in `block (2 levels) in <top (required)>'
       # /home/ubuntu/.rvm/gems/ruby-1.9.3-p429/gems/rspec-core-2.13.1/lib/rspec/core/example.rb:114:in `instance_eval'
       # /home/ubuntu/.rvm/gems/ruby-1.9.3-p429/gems/rspec-core-2.13.1/lib/rspec/core/example.rb:114:in `block in run'
       # /home/ubuntu/.rvm/gems/ruby-1.9.3-p429/gems/rspec-core-2.13.1/lib/rspec/core/example.rb:254:in `with_around_each_hooks'
       # /home/ubuntu/.rvm/gems/ruby-1.9.3-p429/gems/rspec-core-2.13.1/lib/rspec/core/example.rb:111:in `run'
       # /home/ubuntu/.rvm/gems/ruby-1.9.3-p429/gems/rspec-core-2.13.1/lib/rspec/core/example_group.rb:390:in `block in run_examples'
       # /home/ubuntu/.rvm/gems/ruby-1.9.3-p429/gems/rspec-core-2.13.1/lib/rspec/core/example_group.rb:386:in `map'
       # /home/ubuntu/.rvm/gems/ruby-1.9.3-p429/gems/rspec-core-2.13.1/lib/rspec/core/example_group.rb:386:in `run_examples'
       # /home/ubuntu/.rvm/gems/ruby-1.9.3-p429/gems/rspec-core-2.13.1/lib/rspec/core/example_group.rb:371:in `run'
       # /home/ubuntu/.rvm/gems/ruby-1.9.3-p429/gems/rspec-core-2.13.1/lib/rspec/core/command_line.rb:28:in `block (2 levels) in run'
       # /home/ubuntu/.rvm/gems/ruby-1.9.3-p429/gems/rspec-core-2.13.1/lib/rspec/core/command_line.rb:28:in `map'
       # /home/ubuntu/.rvm/gems/ruby-1.9.3-p429/gems/rspec-core-2.13.1/lib/rspec/core/command_line.rb:28:in `block in run'
       # /home/ubuntu/.rvm/gems/ruby-1.9.3-p429/gems/rspec-core-2.13.1/lib/rspec/core/reporter.rb:34:in `report'
       # /home/ubuntu/.rvm/gems/ruby-1.9.3-p429/gems/rspec-core-2.13.1/lib/rspec/core/command_line.rb:25:in `run'
       # /home/ubuntu/.rvm/gems/ruby-1.9.3-p429/gems/rspec-core-2.13.1/lib/rspec/core/runner.rb:80:in `run'
       # /home/ubuntu/.rvm/gems/ruby-1.9.3-p429/gems/rspec-core-2.13.1/lib/rspec/core/runner.rb:17:in `block in autorun'

**Comment by dgutov** [comment]
How are you running the specs? I can see `em-synchrony-1.0.3` in the `gems` directory in your backtrace, which is not a good sign.

With #192, and with the expected user/database/table created, all ActiveRecord specs run successfully here.

**Comment by dgutov** [comment]
To run:

```sh
git clone git@github.com:dgutov/em-synchrony.git
cd em-synchrony
git checkout fix_specs_launch
bundle install
# Set up access to your MySQL and create the database/table/user
bundle exec rspec
```

**Comment by kswope** [comment]
>
How are you running the specs? I can see em-synchrony-1.0.3 in the gems directory in your backtrace, which is not a good sign.

Probably because that post is almost two years old >:-)

**Comment by dgutov** [comment]
No. Why is the gem being loaded from the `gems` dir?

**Comment by kswope** [comment]
I don't understand what you are getting at.  Are you saying a gem shouldn't be in the gems dir?

I haven't run this thing a couple years, I'm not sure if this fixed itself or not.

**Comment by dgutov** [comment]
Did you run the specs from `/gems/em-synchrony-1.0.3/spec/`? That's peculiar, to say the least. Did you at least call `bundle exec rspec`?

If you clone the repository and run specs from there, that will use the gem sources from the current directory subtree.

> I haven't run this thing a couple years

It's fairly easy to set up and run.

**Comment by dgutov** [comment]
Also, I'm not really familiar with RVM, but it seems like the backtrace shows that gems from different versions of Ruby are used. That's also very weird.
