### ISSUE TITLE
Does this support PostgreSQL?

### ISSUE THREAD

**Issue by JohnMerlino1** [igrigorik/em-synchrony#207]
I noticed in the Gemfile, there is a reference to mysql2, but does this also support PostgreSQL for evented programming with EventMachine?

**Comment by dgutov** [comment]
Nope.

**Comment by igrigorik** [comment]
We don't have any bundled drivers, but there are a few other options available:
- https://github.com/royaltm/ruby-em-pg-client
- https://github.com/mperham/em_postgresql
